import type { OperatingCostSettings, Pricing, Store } from "./types";

export const pricing: Pricing = {
  client: {
    simpleFinishing: 5_500,
    normalFinishing: 8_800,
    dirtyFinishing: 11_000,
    deliveryFinishing: 16_500,
    normalFinishingWithPhoto: 11_000,
    wash: 550,
    recheckBaseMonthlyFee: 370_000,
    recheckBaseUnits: 120,
    recheckLowerUnits: 100,
    recheckUpperUnits: 140,
    recheckAdjustmentUnitPrice: 3_083.333333,
  },
  attaToNas: {
    simpleFinishing: 2_250,
    normalFinishing: 4_500,
    dirtyFinishing: 5_500,
    wash: 300,
    photo: 1_000,
    recheck: 2_000,
  },
  nasToWorker: {
    simpleFinishing: 1_250,
    normalFinishing: 2_500,
    dirtyFinishing: 2_750,
    wash: 200,
    photo: 1_000,
    recheck: 2_000,
  },
};

export const operatingCostSettings: OperatingCostSettings = {
  attaStarterKitCostPerStore: 600_000,
  nasMonthlySupplyCostPerStore: 30_000,
  starterKitAccountingMethod: "cash",
};

export const stores: Store[] = [
  {
    id: "hachioji",
    name: "八王子みなみ野店",
    shortName: "八王子",
    category: "actual",
    managedByNas: false,
    managementPartner: "atta",
    displayInventory: 200,
    finishingCount: 125.9,
    normalFinishingCount: 125.9,
    washCount: 685.5,
    photoCount: 0,
    recheckCount: 0,
    recheckWorkers: 0,
    recheckSlots: 0,
    actualMonthlyRevenue: 1_169_021,
    actualDirectCost: 513_810,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["実績売上・実績原価を優先", "仕上げ1名中心の人員制約", "ガリバー側の売上減退傾向"],
    opportunities: ["固定報酬の処理台数基準を再検証", "水洗い負荷と人員配置の最適化"],
  },
  {
    id: "ichinomiya",
    name: "一宮店",
    shortName: "一宮",
    category: "transition",
    managedByNas: false,
    managementPartner: "atta",
    displayInventory: 300,
    finishingCount: 180,
    normalFinishingCount: 180,
    washCount: 396.3,
    photoCount: 150,
    billPhotoAsFinishingBundle: false,
    photoContractConversionRate: 0.5,
    photoContractAdjustmentUnitPrice: 3_083,
    recheckCount: 0,
    recheckWorkers: 0,
    recheckSlots: 0,
    clientNormalFinishingPrice: 7_500,
    directFinishingCostPerUnit: 3_800,
    directPhotoConversionRate: 0.5,
    directPhotoBaseActualUnits: 150,
    directPhotoBaseCompensation: 170_000,
    directWashCostPerUnit: 220,
    directRecheckCostPerUnit: 0,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["通常仕上げ8,250円（税込）／7,500円（税抜）", "仕上げ専任と撮影専任の分業", "仕上げ180台・撮影150台を想定", "撮影150実台×0.5＝75換算台", "撮影契約収益292,925円・撮影専任報酬170,000円", "リチェック業務は対象外"],
    opportunities: ["撮影150台超の場合の人員・報酬条件を再設計", "仕上げと撮影の稼働差を継続監視"],
  },
  {
    id: "shinsayama",
    name: "新狭山店",
    shortName: "新狭山",
    category: "forecast",
    managedByNas: false,
    managementPartner: "liveColor",
    displayInventory: 200,
    finishingCount: 180,
    normalFinishingCount: 180,
    washCount: 0,
    photoCount: 180,
    recheckCount: 180,
    recheckWorkers: 2,
    recheckSlots: 2,
    directFinishingCostPerUnit: 5_500,
    directRecheckCostPerUnit: 2_500,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["LIVE COLOR管理対象", "水洗い業務なし", "仕上げ業務委託費5,500円（税込）／台", "リチェック業務委託費2,500円／台", "月180台・リチェック2枠の想定"],
    opportunities: ["LIVE COLORとの管理条件を実績で検証", "枠別稼働率の平準化", "実績取得後の単価・台数更新"],
  },
  {
    id: "omiya",
    name: "WOW!TOWN大宮店",
    shortName: "大宮",
    category: "forecast",
    managedByNas: true,
    managementPartner: "nas",
    displayInventory: 150,
    finishingCount: 130,
    normalFinishingCount: 130,
    washCount: 0,
    photoCount: 130,
    recheckCount: 130,
    recheckWorkers: 2,
    recheckSlots: 2,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["NaS管理対象", "月130台・リチェック2枠の想定", "展示車両水洗いは対象外"],
    opportunities: ["枠数に対する処理量の適正化"],
  },
  {
    id: "soka",
    name: "草加インター店",
    shortName: "草加",
    category: "forecast",
    managedByNas: true,
    managementPartner: "nas",
    displayInventory: 250,
    finishingCount: 200,
    normalFinishingCount: 200,
    washCount: 400,
    photoCount: 200,
    recheckCount: 200,
    recheckWorkers: 2,
    recheckSlots: 2,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["NaS管理対象", "月200台・リチェック2枠の高稼働想定"],
    opportunities: ["担当者別100台の負荷を継続監視", "消耗品費と粗利の実績差異分析"],
  },
  {
    id: "tsukuba",
    name: "ガリバーつくば研究学園店",
    shortName: "つくば",
    category: "forecast",
    managedByNas: true,
    managementPartner: "nas",
    sourceUrl: "https://221616.com/shop/ibaraki/G01234/",
    displayInventory: 150,
    finishingCount: 150,
    normalFinishingCount: 150,
    washCount: 300,
    photoCount: 0,
    recheckCount: 70,
    recheckWorkers: 1,
    recheckSlots: 1,
    starterKitInstalled: false,
    starterKitCost: 600_000,
    openingMonth: "開設月調整中",
    notes: ["新規依頼店舗", "NaS管理対象", "展示在庫150台想定", "当面は撮影業務なし", "仕上げ・水洗い・リチェックは平均150台店舗モデルで仮置き"],
    opportunities: ["開設月と稼働開始条件の確定", "撮影業務の開始時期を別途判断", "実績取得後の処理台数・人員・枠数更新"],
  },
];

export const defaultExpansionInputs = {
  storeCount: 3,
  finishingCount: 150,
  simpleShare: 0,
  normalShare: 1,
  dirtyShare: 0,
  washCount: 300,
  photoCount: 150,
  recheckCount: 70,
  recheckWorkers: 1,
  recheckSlots: 1,
  managedByNas: true,
} as const;
