import type { OperatingCostSettings, Pricing, Store } from "./types";

export const pricing: Pricing = {
  client: {
    simpleFinishing: 5_500,
    normalFinishing: 8_800,
    dirtyFinishing: 11_000,
    deliveryFinishing: 16_500,
    normalFinishingWithPhoto: 11_000,
    wash: 550,
    recheckBaseMonthlyFee: 370_000,
    recheckBaseUnits: 120,
    recheckLowerUnits: 100,
    recheckUpperUnits: 140,
    recheckAdjustmentUnitPrice: 3_083.333333,
  },
  attaToNas: {
    simpleFinishing: 2_250,
    normalFinishing: 4_500,
    dirtyFinishing: 5_500,
    wash: 300,
    photo: 1_000,
    recheck: 2_000,
  },
  nasToWorker: {
    simpleFinishing: 1_250,
    normalFinishing: 2_500,
    dirtyFinishing: 2_750,
    wash: 200,
    photo: 1_000,
    recheck: 2_000,
  },
};

export const operatingCostSettings: OperatingCostSettings = {
  attaStarterKitCostPerStore: 600_000,
  nasMonthlySupplyCostPerStore: 30_000,
  starterKitAccountingMethod: "cash",
};

export const stores: Store[] = [
  {
    id: "hachioji",
    name: "八王子みなみ野店",
    shortName: "八王子",
    category: "actual",
    managedByNas: false,
    displayInventory: 200,
    finishingCount: 125.9,
    normalFinishingCount: 125.9,
    washCount: 685.5,
    photoCount: 0,
    recheckCount: 0,
    recheckWorkers: 0,
    recheckSlots: 0,
    actualMonthlyRevenue: 1_169_021,
    actualDirectCost: 513_810,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["実績売上・実績原価を優先", "仕上げ1名中心の人員制約", "ガリバー側の売上減退傾向"],
    opportunities: ["固定報酬の処理台数基準を再検証", "水洗い負荷と人員配置の最適化"],
  },
  {
    id: "ichinomiya",
    name: "一宮店",
    shortName: "一宮",
    category: "transition",
    managedByNas: false,
    displayInventory: 300,
    finishingCount: 180,
    normalFinishingCount: 180,
    washCount: 396.3,
    photoCount: 100,
    recheckCount: 70,
    recheckWorkers: 1,
    recheckSlots: 1,
    directFinishingCostPerUnit: 3_800,
    directPhotoConversionRate: 0.5,
    directPhotoBaseActualUnits: 100,
    directPhotoBaseCompensation: 230_000,
    directWashCostPerUnit: 220,
    directRecheckCostPerUnit: 2_000,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["仕上げ専任と撮影専任の分業", "当面は仕上げ180台・撮影100台を想定", "撮影は1実台＝0.5換算、100実台で23万円", "リチェック1名で月70台を初期値"],
    opportunities: ["撮影100台超の場合の人員・報酬条件を再設計", "70台超のリチェック処理能力を段階増強"],
  },
  {
    id: "shinsayama",
    name: "新狭山店",
    shortName: "新狭山",
    category: "forecast",
    managedByNas: true,
    displayInventory: 200,
    finishingCount: 180,
    normalFinishingCount: 180,
    washCount: 360,
    photoCount: 180,
    recheckCount: 180,
    recheckWorkers: 2,
    recheckSlots: 2,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["NaS管理対象", "月180台・リチェック2枠の想定"],
    opportunities: ["枠別稼働率の平準化", "実績取得後の単価・台数更新"],
  },
  {
    id: "omiya",
    name: "WOW!TOWN大宮店",
    shortName: "大宮",
    category: "forecast",
    managedByNas: true,
    displayInventory: 150,
    finishingCount: 130,
    normalFinishingCount: 130,
    washCount: 260,
    photoCount: 130,
    recheckCount: 130,
    recheckWorkers: 2,
    recheckSlots: 2,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["NaS管理対象", "月130台・リチェック2枠の想定"],
    opportunities: ["枠数に対する処理量の適正化", "洗車・仕上げの稼働連動"],
  },
  {
    id: "soka",
    name: "草加インター店",
    shortName: "草加",
    category: "forecast",
    managedByNas: true,
    displayInventory: 250,
    finishingCount: 200,
    normalFinishingCount: 200,
    washCount: 400,
    photoCount: 200,
    recheckCount: 200,
    recheckWorkers: 2,
    recheckSlots: 2,
    starterKitInstalled: true,
    starterKitCost: 600_000,
    openingMonth: "既存店（支出済み）",
    notes: ["NaS管理対象", "月200台・リチェック2枠の高稼働想定"],
    opportunities: ["担当者別100台の負荷を継続監視", "消耗品費と粗利の実績差異分析"],
  },
];

export const defaultExpansionInputs = {
  storeCount: 3,
  finishingCount: 150,
  simpleShare: 0,
  normalShare: 1,
  dirtyShare: 0,
  washCount: 300,
  photoCount: 150,
  recheckCount: 70,
  recheckWorkers: 1,
  recheckSlots: 1,
  managedByNas: true,
} as const;
